### ISSUE TITLE
3 MEMS combined pointcloud

### ISSUE THREAD

**Issue by ryanyej** [PRBonn/depth_clustering#84]
I want to use 4 mems-lidar combined pointcloud for close distance cluster, however I found ground point remover wasn't so ideal.
What went wrong?  
Do I have to  assume combined 3 mems into one  sensor?

**Comment by niosus** [comment]
Hey @ryanyej thanks for your question. Unfortunately, the code has been designed to process the output from a single sensor. As long as your sensor has some structured output, i.e., you can represent your full scan as a depth image, you should be able to use the algorithm. If this is not the case, then you will probably have to look elsewhere or find a method to make your data structured. If you have a number of mems lidars, you might create a single "fake" sensor by projecting the 3D points of the combined point clouds onto a virtual range image or you could perform clustering on a per-sensor basis and combine the segments afterwards. 
I'm not sure I can be of any help further though, so I will close this issue, but feel free to reopen it if you think otherwise.
